name: xprinter_app
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  image: ^3.2.0 
  socket_io_client: ^2.0.0
  cupertino_icons: ^1.0.8
  hive: ^2.2.3  # Updated to the latest stable version
  hive_flutter: ^1.1.0  # Updated to the latest stable version
  path_provider: ^2.1.1  # Add this for Hive initialization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.4  # Updated to the latest stable version
  hive_generator: ^2.0.1  # Updated to the latest stable version

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg  # Add your image here